version: 2
project_name: cortextool
builds:
  - id: cortextool-linux
    ldflags:
      -s -w -X registry.gitlab.com/iot-optimisation/experiments/cortex-tools/pkg/version.Version={{.Version}}
    binary: cortextool
    env:
      - CGO_ENABLED=0
    main: ./cmd/cortextool/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    ids:
      - cortextool-linux
    dockerfile: cmd/cortextool/GR.Dockerfile
    image_templates:
      - "registry.gitlab.com/iot-optimisation/experiments/cortex-tools:latest-amd64"
      - "registry.gitlab.com/iot-optimisation/experiments/cortex-tools:{{ .Tag }}-amd64"
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=repository=https://registry.gitlab.com/iot-optimisation/experiments/cortex-tools"
    - "--label=homepage=https://grafana.com"
  - goos: linux
    goarch: arm64
    use: buildx
    ids:
      - cortextool-linux
    dockerfile: cmd/cortextool/GR.Dockerfile
    image_templates:
      - "registry.gitlab.com/iot-optimisation/experiments/cortex-tools:latest-arm64"
      - "registry.gitlab.com/iot-optimisation/experiments/cortex-tools:{{ .Tag }}-arm64"
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=repository=https://registry.gitlab.com/iot-optimisation/experiments/cortex-tools"
    - "--label=homepage=https://grafana.com"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: registry.gitlab.com/iot-optimisation/experiments/cortex-tools:{{ .Version }}
    image_templates:
      - registry.gitlab.com/iot-optimisation/experiments/cortex-tools:{{ .Version }}-amd64
      - registry.gitlab.com/iot-optimisation/experiments/cortex-tools:{{ .Version }}-arm64
  - name_template: registry.gitlab.com/iot-optimisation/experiments/cortex-tools:latest
    image_templates:
      - registry.gitlab.com/iot-optimisation/experiments/cortex-tools:latest-amd64
      - registry.gitlab.com/iot-optimisation/experiments/cortex-tools:latest-arm64
